//
// MusicItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MusicItem: Codable {

    public var guid: String?
    public var name: String?
    public var _description: String?
    public var imageUrl: String?

    public init(guid: String?, name: String?, _description: String?, imageUrl: String?) {
        self.guid = guid
        self.name = name
        self._description = _description
        self.imageUrl = imageUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case guid
        case name
        case _description = "description"
        case imageUrl = "image_url"
    }


}

